### ISSUE TITLE
Notification action wrong

### ISSUE THREAD

**Issue by 3d-gussner** [sarusani/OctoPrint-ActivatePrusaHostTimer#4]
While testing the Plug-in found that the Notification action isn't working correctly.

https://github.com/sarusani/OctoPrint-ActivatePrusaHostTimer/blob/main/octoprint_ActivatePrusaHostTimer/__init__.py#L101

Between `//` and `action` a `SPACE` is needed. 
`self._printer.commands("M118 // action:notification %s" % (text))` works correctly.

Question: Why do you send from OctoPrint `M118` to send back the message to OctoPrint. Isn't there a way to show notifications within OctoPrint when it receives the `// action:ready` or `// action:not_ready`?

**Comment by sarusani** [comment]
I chose to use M118 so other plugins that work with actions can also intercept them. But since they are only messages this is probably not really needed... 😄 

I recently changed `M118 // action:notification %s" % (text)` to `M118 A1 action:notification %s" % (text)`. That's the correct use according to [marlin](https://marlinfw.org/docs/gcode/M118.html
) & [prusa](https://help.prusa3d.com/article/prusa-firmware-specific-g-code-commands_112173)  documentation.
But this won't add a space. If that's a requirement, we need to fix `case 118` in the [MK3 Firmware](https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/Marlin_main.cpp).

It's working for me without the space. Do you get an error, or is the notification just not showing for you?

**Comment by sarusani** [comment]
Just saw that the [reprap wiki](https://reprap.org/wiki/G-code#Action_commands) also doesn't mention a space between // and action. So I think the Firmware implementation is correct.
I will just switch to trigger the notification internally. So it will work for sure.

Thanks for the report!

PS:
Turns out that I can't figure out how to set notifications internally... Back to using M118

**Comment by 3d-gussner** [comment]
@sarusani See https://docs.octoprint.org/en/master/features/action_commands.html

**Comment by sarusani** [comment]
@3d-gussner 
There's conflicting info in the documentation. 🤷 
See examples in:
https://docs.octoprint.org/en/master/bundledplugins/action_command_notification.html
https://docs.octoprint.org/en/master/bundledplugins/action_command_prompt.html

I'll ask around in the OctoPrint forum to see what I can do. I'd prefer to stick to the marlin documentation and to use "M118 A1 action:notification" instead of hardcoding it.

Thanks again! I'll update the issue as soon as I have some more insight.

**Comment by sarusani** [comment]
@3d-gussner 
I didn't get a lot of usable responses on my inquiries. So I looked at the OctoPrint code. It uses stip(), so whitespaces get removed anyway.  As long as the strings "//","action:"&"{command}" (no matter how many spaces are in between of them) are received, it will parse it.

So sticking with reprap/marlin and removing the space, like you did in the Firmware PR, is definitely the proper thing to do. 👍

**Comment by 3d-gussner** [comment]
@sarusani While testing active `Show printer notifications` causes issues during reprint of a host print.
1. Activate `Show printer notifications`
2. Start Octoprint print
3. Let it finish
4. Select on LCD Reprint`
```
Recv: //action:start
(Re)Starting current job on request of the printer...
Changing monitoring state from "Operational" to "Starting"
Send: N0 M110 N0*125
Recv: ok
Send: N1 M118 A1 action:notification Printer is ready. Printing: Shape-Box_0.2mm_PLA_MK3S_8m.gcode*112
Recv: Error:checksum mismatch, Last Line: 0
Recv: Resend: 1
```
Even when the Plugin is paused it sends the `M118` messages and so fails to Reprint.
![image](https://github.com/sarusani/OctoPrint-ActivatePrusaHostTimer/assets/25530011/8cf56001-44f2-42a8-9204-44d647eaa171)

**Comment by sarusani** [comment]
Thank you so much for testing!
I noticed the error and knew it has something to do with the plugin, but I somehow convinced myself it's related to a problem in my "_startPrint" function. So I kept looking in the wrong place...
Thanks for making me aware that it's actually a problem of the notification!

**Comment by sarusani** [comment]
I removed showing notifications for action:start (reprints) completely. There's no way to make it work reliably without risking a communication error. I also made some changes to make sure this should not happen when starting a print with "Set ready".
