### ISSUE TITLE
Version 1.0.0 broken detection

### ISSUE THREAD

**Issue by 3d-gussner** [sarusani/OctoPrint-ActivatePrusaHostTimer#6]
The implemented detection doesn't work and so the whole Plugin doesn't work anymore.

If you want to detect if the printer that supports `M79` send it and if it answers with `ok`.
Printers normally answer with `echo:Unknown command: "M79"`
 
If you want to detect a Prusa printer type use `M862.2 Q` and `M862.3 Q` see also [here](https://prusa3d.github.io/Prusa-Firmware-Doc/Prusa-Firmware/printers_8h_source.html) and [here](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/master/src/common/gcode/gcode_info.cpp#L52-L73)

MK3S and MK3S+ : results are `302` and `MK3S`
MK3S/+ and MMU3:  results are `30302` and `MK3SMMU3`
MK4 : results are `M862.2 P130` and `M862.3 P "MK4"`
MK4 and MMu3 results are : `M862.2 P30130` and `M862.3 P "MK4MMU3"`

**Comment by sarusani** [comment]
Currently I only do a very rudimentary "detection" by checking the printer profile->model field.
I can reproduce your error when "Auto-connect on server startup" is not selected. (Or the printer is not connected during startup for other reasons)
Am I correct to assume that's the case on your setup?
I pushed a bugfix for that case, so I have time to look into proper detection. (The plugin currently only hocks into action commands, so I cant easily read the response of M79 or M862)

**Comment by 3d-gussner** [comment]
I see, but as the "model" in the Octoprint Profile settings is a "free" editable text users as I may enter `Prusa MK3S` or something else which breaks the Plugin.
I described two ways how you can "test" is the printer supports this.
Actually thinking about it sending `M79` and getting an `ok` back should be sufficient.
Using The `M862.2 Q` and `M862.3 Q`  would need another check which firmware is installed with `M862.4 Q`

**Comment by sarusani** [comment]
I only check if I can find the substring "mk3" in the model field. If not, I show a warning on the setup page. The plugin functionality is currently not dependent on this. Only the visual warning.

 I'll look into a proper solution during the holidays. (I also think that a M79 check should be sufficient.)

PS: The reason 1.0.0 didn't send M79 when no printer was detected during startup, was not the plugin refusing to send it because it didn't detected a mk3, it was a coding error when the API returned a empty object.

**Comment by 3d-gussner** [comment]
Works again in 1.0.1 thanks
